-- 015_finance.sql - full crypto finance plane: deterministic multi-chain
-- deposit addresses, superadmin-signed withdrawal pipeline with sub-second
-- auto-approval, escrow-backed P2P marketplace with local payment rails for
-- every supported country, crypto convert engine, and dynamic admin roles.
BEGIN;

-- Per-feature switches so superadmin/finance control exactly which tokens can
-- be deposited, withdrawn, P2P-traded and converted.
ALTER TABLE platform_tokens
  ADD COLUMN IF NOT EXISTS deposit_enabled  BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS withdraw_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS p2p_enabled      BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS convert_enabled  BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS min_withdraw     NUMERIC(38,18) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdraw_fee     NUMERIC(38,18) NOT NULL DEFAULT 0;

-- Deterministic per-user deposit addresses derived in Go from
-- WALLET_MASTER_SEED (HMAC chain codes). The derivation path is stored so
-- custody-provider addresses can later replace self-custody ones cleanly.
CREATE TABLE IF NOT EXISTS deposit_addresses (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  asset        TEXT NOT NULL,
  chain        TEXT NOT NULL,
  address      TEXT NOT NULL,
  derivation   TEXT NOT NULL,
  created_at   TIMESTAMPTZ DEFAULT now(),
  UNIQUE (user_id, asset, chain),
  UNIQUE (chain, address)
);
CREATE INDEX IF NOT EXISTS idx_deposit_addr_user ON deposit_addresses(user_id);

-- Every withdrawal is a signed request. Status flow:
--   pending_review -> approved -> signed -> completed
--                            \-> rejected
-- The policy engine auto-approves + auto-signs clean requests in the same
-- transaction (<1s end to end). Flagged requests wait for an explicit
-- superadmin signature. Admins can approve/reject but can NEVER redirect or
-- execute funds themselves: execution binds the immutable to_address stored
-- at request time, and the ledger debit happens only here.
CREATE TABLE IF NOT EXISTS withdrawal_requests (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  asset         TEXT NOT NULL,
  chain         TEXT NOT NULL,
  to_address    TEXT NOT NULL,
  amount        NUMERIC(38,18) NOT NULL CHECK (amount > 0),
  fee           NUMERIC(38,18) NOT NULL DEFAULT 0,
  status        TEXT NOT NULL DEFAULT 'pending_review'
                CHECK (status IN ('pending_review','approved','signed','completed','rejected','failed')),
  risk_score    INT NOT NULL DEFAULT 0,
  risk_flags    TEXT[] NOT NULL DEFAULT '{}',
  auto_approved BOOLEAN NOT NULL DEFAULT false,
  approved_by   TEXT,
  approved_at   TIMESTAMPTZ,
  signature     TEXT,
  signed_at     TIMESTAMPTZ,
  tx_hash       TEXT,
  ledger_tx     UUID,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_withdraw_user ON withdrawal_requests(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_withdraw_status ON withdrawal_requests(status) WHERE status IN ('pending_review','approved','signed');

-- Superadmin-defined roles with a permission set. Built-in roles are seeded;
-- custom roles (e.g. p2p_manager, convert_manager, withdrawal_reviewer) can
-- be created/deleted at runtime. admin_roles.role references these defs.
CREATE TABLE IF NOT EXISTS admin_role_defs (
  name         TEXT PRIMARY KEY,
  description  TEXT NOT NULL DEFAULT '',
  permissions  TEXT[] NOT NULL DEFAULT '{}',
  built_in     BOOLEAN NOT NULL DEFAULT false,
  created_by   UUID REFERENCES users(id),
  created_at   TIMESTAMPTZ DEFAULT now()
);

INSERT INTO admin_role_defs (name, description, permissions, built_in) VALUES
  ('superadmin',  'Full control of every admin surface', ARRAY['*'], true),
  ('moderator',   'Reports, user status, content moderation', ARRAY['reports.review','users.status','stats.view'], true),
  ('support',     'Read-only user lookup and KYC queue', ARRAY['users.view','kyc.view','stats.view'], true),
  ('finance',     'KYC review, payouts, platform tokens, withdrawals, convert rates, P2P disputes', ARRAY['kyc.review','payouts.review','tokens.manage','withdrawals.review','convert.manage','p2p.resolve','stats.view'], true),
  ('ads_reviewer','Ad campaign review', ARRAY['ads.review','stats.view'], true)
ON CONFLICT (name) DO NOTHING;

-- Local payment rails per country (mobile money, bank, e-wallet, cash).
CREATE TABLE IF NOT EXISTS p2p_payment_methods (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country_iso  TEXT NOT NULL,
  name         TEXT NOT NULL,
  kind         TEXT NOT NULL CHECK (kind IN ('mobile_money','bank_transfer','ewallet','cash','card')),
  created_at   TIMESTAMPTZ DEFAULT now(),
  UNIQUE (country_iso, name)
);

-- Buy/sell advertisements. Price is fiat per 1 unit of the crypto asset.
CREATE TABLE IF NOT EXISTS p2p_offers (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  side            TEXT NOT NULL CHECK (side IN ('buy','sell')),
  asset           TEXT NOT NULL,
  chain           TEXT NOT NULL,
  fiat_currency   TEXT NOT NULL,
  country_iso     TEXT NOT NULL,
  price           NUMERIC(38,18) NOT NULL CHECK (price > 0),
  min_amount      NUMERIC(38,18) NOT NULL DEFAULT 0,
  max_amount      NUMERIC(38,18) NOT NULL CHECK (max_amount > 0),
  payment_methods TEXT[] NOT NULL DEFAULT '{}',
  terms           TEXT NOT NULL DEFAULT '',
  active          BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_p2p_offers ON p2p_offers(asset, chain, country_iso, side) WHERE active;

-- Escrowed trades. Crypto is locked at open, released on completion.
CREATE TABLE IF NOT EXISTS p2p_trades (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  offer_id       UUID NOT NULL REFERENCES p2p_offers(id),
  buyer_id       UUID NOT NULL REFERENCES users(id),
  seller_id      UUID NOT NULL REFERENCES users(id),
  asset          TEXT NOT NULL,
  chain          TEXT NOT NULL,
  crypto_amount  NUMERIC(38,18) NOT NULL CHECK (crypto_amount > 0),
  fiat_amount    NUMERIC(38,18) NOT NULL CHECK (fiat_amount > 0),
  fiat_currency  TEXT NOT NULL,
  payment_method TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'open'
                 CHECK (status IN ('open','paid','completed','cancelled','disputed','resolved_buyer','resolved_seller')),
  escrow_tx      UUID,
  release_tx     UUID,
  paid_at        TIMESTAMPTZ,
  created_at     TIMESTAMPTZ DEFAULT now(),
  updated_at     TIMESTAMPTZ DEFAULT now(),
  CHECK (buyer_id <> seller_id)
);
CREATE INDEX IF NOT EXISTS idx_p2p_trades_buyer ON p2p_trades(buyer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_p2p_trades_seller ON p2p_trades(seller_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_p2p_trades_disputes ON p2p_trades(status) WHERE status = 'disputed';

-- Admin-maintained USD rates. Conversion executes atomically in the
-- double-entry ledger.
CREATE TABLE IF NOT EXISTS convert_rates (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  asset       TEXT NOT NULL,
  chain       TEXT NOT NULL,
  usd_rate    NUMERIC(38,18) NOT NULL CHECK (usd_rate > 0),
  updated_by  UUID REFERENCES users(id),
  updated_at  TIMESTAMPTZ DEFAULT now(),
  UNIQUE (asset, chain)
);

CREATE TABLE IF NOT EXISTS conversions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  from_asset  TEXT NOT NULL,
  from_chain  TEXT NOT NULL,
  to_asset    TEXT NOT NULL,
  to_chain    TEXT NOT NULL,
  from_amount NUMERIC(38,18) NOT NULL CHECK (from_amount > 0),
  to_amount   NUMERIC(38,18) NOT NULL CHECK (to_amount > 0),
  rate        NUMERIC(38,18) NOT NULL,
  ledger_tx   UUID NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_conversions_user ON conversions(user_id, created_at DESC);

INSERT INTO convert_rates (asset, chain, usd_rate) VALUES
  ('BTC','bitcoin','65000'), ('ETH','ethereum','3200'), ('SOL','solana','145'),
  ('BNB','bsc','580'), ('MATIC','polygon','0.72'),
  ('USDT','ethereum','1'), ('USDT','tron','1'), ('USDT','bsc','1'), ('USDT','polygon','1'),
  ('USDC','ethereum','1'), ('USDC','polygon','1'), ('USDC','solana','1'), ('USDC','base','1'),
  ('USD','internal','1')
ON CONFLICT (asset, chain) DO NOTHING;

-- Payment rails for every supported country (named local methods plus the
-- generic bank / mobile-money / cash rails).
INSERT INTO p2p_payment_methods (country_iso, name, kind) VALUES
  ('AF', 'M-Paisa', 'mobile_money'),
  ('AF', 'HesabPay', 'mobile_money'),
  ('AF', 'Bank transfer', 'bank_transfer'),
  ('AF', 'Mobile money', 'mobile_money'),
  ('AF', 'Cash in person', 'cash'),
  ('AL', 'Bank transfer', 'bank_transfer'),
  ('AL', 'Mobile money', 'mobile_money'),
  ('AL', 'Cash in person', 'cash'),
  ('DZ', 'BaridiMob', 'mobile_money'),
  ('DZ', 'CCP transfer', 'bank_transfer'),
  ('DZ', 'Bank transfer', 'bank_transfer'),
  ('DZ', 'Mobile money', 'mobile_money'),
  ('DZ', 'Cash in person', 'cash'),
  ('AS', 'Bank transfer', 'bank_transfer'),
  ('AS', 'Mobile money', 'mobile_money'),
  ('AS', 'Cash in person', 'cash'),
  ('AD', 'Bank transfer', 'bank_transfer'),
  ('AD', 'Mobile money', 'mobile_money'),
  ('AD', 'Cash in person', 'cash'),
  ('AO', 'Bank transfer', 'bank_transfer'),
  ('AO', 'Mobile money', 'mobile_money'),
  ('AO', 'Cash in person', 'cash'),
  ('AI', 'Bank transfer', 'bank_transfer'),
  ('AI', 'Mobile money', 'mobile_money'),
  ('AI', 'Cash in person', 'cash'),
  ('AG', 'Bank transfer', 'bank_transfer'),
  ('AG', 'Mobile money', 'mobile_money'),
  ('AG', 'Cash in person', 'cash'),
  ('AR', 'Mercado Pago', 'ewallet'),
  ('AR', 'Uala', 'ewallet'),
  ('AR', 'Bank transfer', 'bank_transfer'),
  ('AR', 'Mobile money', 'mobile_money'),
  ('AR', 'Cash in person', 'cash'),
  ('AM', 'Bank transfer', 'bank_transfer'),
  ('AM', 'Mobile money', 'mobile_money'),
  ('AM', 'Cash in person', 'cash'),
  ('AW', 'Bank transfer', 'bank_transfer'),
  ('AW', 'Mobile money', 'mobile_money'),
  ('AW', 'Cash in person', 'cash'),
  ('AU', 'PayID', 'bank_transfer'),
  ('AU', 'Osko', 'bank_transfer'),
  ('AU', 'PayPal', 'ewallet'),
  ('AU', 'Bank transfer', 'bank_transfer'),
  ('AU', 'Mobile money', 'mobile_money'),
  ('AU', 'Cash in person', 'cash'),
  ('AT', 'SEPA transfer', 'bank_transfer'),
  ('AT', 'PayPal', 'ewallet'),
  ('AT', 'Bank transfer', 'bank_transfer'),
  ('AT', 'Mobile money', 'mobile_money'),
  ('AT', 'Cash in person', 'cash'),
  ('AZ', 'Bank transfer', 'bank_transfer'),
  ('AZ', 'Mobile money', 'mobile_money'),
  ('AZ', 'Cash in person', 'cash'),
  ('BS', 'Bank transfer', 'bank_transfer'),
  ('BS', 'Mobile money', 'mobile_money'),
  ('BS', 'Cash in person', 'cash'),
  ('BH', 'Bank transfer', 'bank_transfer'),
  ('BH', 'Mobile money', 'mobile_money'),
  ('BH', 'Cash in person', 'cash'),
  ('BD', 'bKash', 'mobile_money'),
  ('BD', 'Nagad', 'mobile_money'),
  ('BD', 'Rocket', 'mobile_money'),
  ('BD', 'Upay', 'mobile_money'),
  ('BD', 'Bank transfer', 'bank_transfer'),
  ('BD', 'Mobile money', 'mobile_money'),
  ('BD', 'Cash in person', 'cash'),
  ('BB', 'Bank transfer', 'bank_transfer'),
  ('BB', 'Mobile money', 'mobile_money'),
  ('BB', 'Cash in person', 'cash'),
  ('BY', 'Bank transfer', 'bank_transfer'),
  ('BY', 'Mobile money', 'mobile_money'),
  ('BY', 'Cash in person', 'cash'),
  ('BE', 'Payconiq', 'mobile_money'),
  ('BE', 'SEPA transfer', 'bank_transfer'),
  ('BE', 'Bank transfer', 'bank_transfer'),
  ('BE', 'Mobile money', 'mobile_money'),
  ('BE', 'Cash in person', 'cash'),
  ('BZ', 'Bank transfer', 'bank_transfer'),
  ('BZ', 'Mobile money', 'mobile_money'),
  ('BZ', 'Cash in person', 'cash'),
  ('BJ', 'Bank transfer', 'bank_transfer'),
  ('BJ', 'Mobile money', 'mobile_money'),
  ('BJ', 'Cash in person', 'cash'),
  ('BM', 'Bank transfer', 'bank_transfer'),
  ('BM', 'Mobile money', 'mobile_money'),
  ('BM', 'Cash in person', 'cash'),
  ('BT', 'Bank transfer', 'bank_transfer'),
  ('BT', 'Mobile money', 'mobile_money'),
  ('BT', 'Cash in person', 'cash'),
  ('BO', 'Bank transfer', 'bank_transfer'),
  ('BO', 'Mobile money', 'mobile_money'),
  ('BO', 'Cash in person', 'cash'),
  ('BA', 'Bank transfer', 'bank_transfer'),
  ('BA', 'Mobile money', 'mobile_money'),
  ('BA', 'Cash in person', 'cash'),
  ('BW', 'Bank transfer', 'bank_transfer'),
  ('BW', 'Mobile money', 'mobile_money'),
  ('BW', 'Cash in person', 'cash'),
  ('BV', 'Bank transfer', 'bank_transfer'),
  ('BV', 'Mobile money', 'mobile_money'),
  ('BV', 'Cash in person', 'cash'),
  ('BR', 'Pix', 'mobile_money'),
  ('BR', 'PicPay', 'ewallet'),
  ('BR', 'Mercado Pago', 'ewallet'),
  ('BR', 'Bank transfer', 'bank_transfer'),
  ('BR', 'Mobile money', 'mobile_money'),
  ('BR', 'Cash in person', 'cash'),
  ('IO', 'Bank transfer', 'bank_transfer'),
  ('IO', 'Mobile money', 'mobile_money'),
  ('IO', 'Cash in person', 'cash'),
  ('VG', 'Bank transfer', 'bank_transfer'),
  ('VG', 'Mobile money', 'mobile_money'),
  ('VG', 'Cash in person', 'cash'),
  ('BN', 'Bank transfer', 'bank_transfer'),
  ('BN', 'Mobile money', 'mobile_money'),
  ('BN', 'Cash in person', 'cash'),
  ('BG', 'Bank transfer', 'bank_transfer'),
  ('BG', 'Mobile money', 'mobile_money'),
  ('BG', 'Cash in person', 'cash'),
  ('BF', 'Bank transfer', 'bank_transfer'),
  ('BF', 'Mobile money', 'mobile_money'),
  ('BF', 'Cash in person', 'cash'),
  ('BI', 'Bank transfer', 'bank_transfer'),
  ('BI', 'Mobile money', 'mobile_money'),
  ('BI', 'Cash in person', 'cash'),
  ('KH', 'ABA Pay', 'mobile_money'),
  ('KH', 'Wing Money', 'mobile_money'),
  ('KH', 'Pi Pay', 'ewallet'),
  ('KH', 'Bank transfer', 'bank_transfer'),
  ('KH', 'Mobile money', 'mobile_money'),
  ('KH', 'Cash in person', 'cash'),
  ('CM', 'MTN MoMo', 'mobile_money'),
  ('CM', 'Orange Money', 'mobile_money'),
  ('CM', 'Bank transfer', 'bank_transfer'),
  ('CM', 'Mobile money', 'mobile_money'),
  ('CM', 'Cash in person', 'cash'),
  ('CV', 'Bank transfer', 'bank_transfer'),
  ('CV', 'Mobile money', 'mobile_money'),
  ('CV', 'Cash in person', 'cash'),
  ('KY', 'Bank transfer', 'bank_transfer'),
  ('KY', 'Mobile money', 'mobile_money'),
  ('KY', 'Cash in person', 'cash'),
  ('CF', 'Bank transfer', 'bank_transfer'),
  ('CF', 'Mobile money', 'mobile_money'),
  ('CF', 'Cash in person', 'cash'),
  ('TD', 'Bank transfer', 'bank_transfer'),
  ('TD', 'Mobile money', 'mobile_money'),
  ('TD', 'Cash in person', 'cash'),
  ('CL', 'MACH', 'ewallet'),
  ('CL', 'Bank transfer', 'bank_transfer'),
  ('CL', 'Mobile money', 'mobile_money'),
  ('CL', 'Cash in person', 'cash'),
  ('CN', 'Alipay', 'ewallet'),
  ('CN', 'WeChat Pay', 'ewallet'),
  ('CN', 'UnionPay', 'card'),
  ('CN', 'Bank transfer', 'bank_transfer'),
  ('CN', 'Mobile money', 'mobile_money'),
  ('CN', 'Cash in person', 'cash'),
  ('CX', 'Bank transfer', 'bank_transfer'),
  ('CX', 'Mobile money', 'mobile_money'),
  ('CX', 'Cash in person', 'cash'),
  ('CC', 'Bank transfer', 'bank_transfer'),
  ('CC', 'Mobile money', 'mobile_money'),
  ('CC', 'Cash in person', 'cash'),
  ('CO', 'Nequi', 'mobile_money'),
  ('CO', 'Daviplata', 'mobile_money'),
  ('CO', 'PSE', 'bank_transfer'),
  ('CO', 'Bank transfer', 'bank_transfer'),
  ('CO', 'Mobile money', 'mobile_money'),
  ('CO', 'Cash in person', 'cash'),
  ('KM', 'Bank transfer', 'bank_transfer'),
  ('KM', 'Mobile money', 'mobile_money'),
  ('KM', 'Cash in person', 'cash'),
  ('CG', 'Bank transfer', 'bank_transfer'),
  ('CG', 'Mobile money', 'mobile_money'),
  ('CG', 'Cash in person', 'cash'),
  ('CK', 'Bank transfer', 'bank_transfer'),
  ('CK', 'Mobile money', 'mobile_money'),
  ('CK', 'Cash in person', 'cash'),
  ('CR', 'Bank transfer', 'bank_transfer'),
  ('CR', 'Mobile money', 'mobile_money'),
  ('CR', 'Cash in person', 'cash'),
  ('HR', 'Bank transfer', 'bank_transfer'),
  ('HR', 'Mobile money', 'mobile_money'),
  ('HR', 'Cash in person', 'cash'),
  ('CU', 'Bank transfer', 'bank_transfer'),
  ('CU', 'Mobile money', 'mobile_money'),
  ('CU', 'Cash in person', 'cash'),
  ('CW', 'Bank transfer', 'bank_transfer'),
  ('CW', 'Mobile money', 'mobile_money'),
  ('CW', 'Cash in person', 'cash'),
  ('CY', 'Bank transfer', 'bank_transfer'),
  ('CY', 'Mobile money', 'mobile_money'),
  ('CY', 'Cash in person', 'cash'),
  ('CZ', 'Bank transfer', 'bank_transfer'),
  ('CZ', 'Mobile money', 'mobile_money'),
  ('CZ', 'Cash in person', 'cash'),
  ('CD', 'Bank transfer', 'bank_transfer'),
  ('CD', 'Mobile money', 'mobile_money'),
  ('CD', 'Cash in person', 'cash'),
  ('DK', 'MobilePay', 'mobile_money'),
  ('DK', 'Bank transfer', 'bank_transfer'),
  ('DK', 'Mobile money', 'mobile_money'),
  ('DK', 'Cash in person', 'cash'),
  ('DJ', 'Bank transfer', 'bank_transfer'),
  ('DJ', 'Mobile money', 'mobile_money'),
  ('DJ', 'Cash in person', 'cash'),
  ('DM', 'Bank transfer', 'bank_transfer'),
  ('DM', 'Mobile money', 'mobile_money'),
  ('DM', 'Cash in person', 'cash'),
  ('EC', 'Bank transfer', 'bank_transfer'),
  ('EC', 'Mobile money', 'mobile_money'),
  ('EC', 'Cash in person', 'cash'),
  ('EG', 'Vodafone Cash', 'mobile_money'),
  ('EG', 'Orange Cash', 'mobile_money'),
  ('EG', 'Fawry', 'ewallet'),
  ('EG', 'InstaPay', 'bank_transfer'),
  ('EG', 'Bank transfer', 'bank_transfer'),
  ('EG', 'Mobile money', 'mobile_money'),
  ('EG', 'Cash in person', 'cash'),
  ('SV', 'Bank transfer', 'bank_transfer'),
  ('SV', 'Mobile money', 'mobile_money'),
  ('SV', 'Cash in person', 'cash'),
  ('GQ', 'Bank transfer', 'bank_transfer'),
  ('GQ', 'Mobile money', 'mobile_money'),
  ('GQ', 'Cash in person', 'cash'),
  ('ER', 'Bank transfer', 'bank_transfer'),
  ('ER', 'Mobile money', 'mobile_money'),
  ('ER', 'Cash in person', 'cash'),
  ('EE', 'Bank transfer', 'bank_transfer'),
  ('EE', 'Mobile money', 'mobile_money'),
  ('EE', 'Cash in person', 'cash'),
  ('SZ', 'Bank transfer', 'bank_transfer'),
  ('SZ', 'Mobile money', 'mobile_money'),
  ('SZ', 'Cash in person', 'cash'),
  ('ET', 'Telebirr', 'mobile_money'),
  ('ET', 'Amole', 'mobile_money'),
  ('ET', 'Bank transfer', 'bank_transfer'),
  ('ET', 'Mobile money', 'mobile_money'),
  ('ET', 'Cash in person', 'cash'),
  ('FK', 'Bank transfer', 'bank_transfer'),
  ('FK', 'Mobile money', 'mobile_money'),
  ('FK', 'Cash in person', 'cash'),
  ('FO', 'Bank transfer', 'bank_transfer'),
  ('FO', 'Mobile money', 'mobile_money'),
  ('FO', 'Cash in person', 'cash'),
  ('FJ', 'Bank transfer', 'bank_transfer'),
  ('FJ', 'Mobile money', 'mobile_money'),
  ('FJ', 'Cash in person', 'cash'),
  ('FI', 'MobilePay', 'mobile_money'),
  ('FI', 'SEPA transfer', 'bank_transfer'),
  ('FI', 'Bank transfer', 'bank_transfer'),
  ('FI', 'Mobile money', 'mobile_money'),
  ('FI', 'Cash in person', 'cash'),
  ('FR', 'SEPA transfer', 'bank_transfer'),
  ('FR', 'PayPal', 'ewallet'),
  ('FR', 'Lydia', 'ewallet'),
  ('FR', 'Bank transfer', 'bank_transfer'),
  ('FR', 'Mobile money', 'mobile_money'),
  ('FR', 'Cash in person', 'cash'),
  ('GF', 'Bank transfer', 'bank_transfer'),
  ('GF', 'Mobile money', 'mobile_money'),
  ('GF', 'Cash in person', 'cash'),
  ('PF', 'Bank transfer', 'bank_transfer'),
  ('PF', 'Mobile money', 'mobile_money'),
  ('PF', 'Cash in person', 'cash'),
  ('TF', 'Bank transfer', 'bank_transfer'),
  ('TF', 'Mobile money', 'mobile_money'),
  ('TF', 'Cash in person', 'cash'),
  ('GA', 'Bank transfer', 'bank_transfer'),
  ('GA', 'Mobile money', 'mobile_money'),
  ('GA', 'Cash in person', 'cash'),
  ('GM', 'Bank transfer', 'bank_transfer'),
  ('GM', 'Mobile money', 'mobile_money'),
  ('GM', 'Cash in person', 'cash'),
  ('GE', 'Bank transfer', 'bank_transfer'),
  ('GE', 'Mobile money', 'mobile_money'),
  ('GE', 'Cash in person', 'cash'),
  ('DE', 'SEPA transfer', 'bank_transfer'),
  ('DE', 'PayPal', 'ewallet'),
  ('DE', 'Revolut', 'ewallet'),
  ('DE', 'Bank transfer', 'bank_transfer'),
  ('DE', 'Mobile money', 'mobile_money'),
  ('DE', 'Cash in person', 'cash'),
  ('GH', 'MTN MoMo', 'mobile_money'),
  ('GH', 'Vodafone Cash', 'mobile_money'),
  ('GH', 'AirtelTigo Money', 'mobile_money'),
  ('GH', 'Bank transfer', 'bank_transfer'),
  ('GH', 'Mobile money', 'mobile_money'),
  ('GH', 'Cash in person', 'cash'),
  ('GI', 'Bank transfer', 'bank_transfer'),
  ('GI', 'Mobile money', 'mobile_money'),
  ('GI', 'Cash in person', 'cash'),
  ('GR', 'IRIS', 'mobile_money'),
  ('GR', 'SEPA transfer', 'bank_transfer'),
  ('GR', 'Bank transfer', 'bank_transfer'),
  ('GR', 'Mobile money', 'mobile_money'),
  ('GR', 'Cash in person', 'cash'),
  ('GL', 'Bank transfer', 'bank_transfer'),
  ('GL', 'Mobile money', 'mobile_money'),
  ('GL', 'Cash in person', 'cash'),
  ('GD', 'Bank transfer', 'bank_transfer'),
  ('GD', 'Mobile money', 'mobile_money'),
  ('GD', 'Cash in person', 'cash'),
  ('GP', 'Bank transfer', 'bank_transfer'),
  ('GP', 'Mobile money', 'mobile_money'),
  ('GP', 'Cash in person', 'cash'),
  ('GU', 'Bank transfer', 'bank_transfer'),
  ('GU', 'Mobile money', 'mobile_money'),
  ('GU', 'Cash in person', 'cash'),
  ('GT', 'Bank transfer', 'bank_transfer'),
  ('GT', 'Mobile money', 'mobile_money'),
  ('GT', 'Cash in person', 'cash'),
  ('GG', 'Bank transfer', 'bank_transfer'),
  ('GG', 'Mobile money', 'mobile_money'),
  ('GG', 'Cash in person', 'cash'),
  ('GN', 'Bank transfer', 'bank_transfer'),
  ('GN', 'Mobile money', 'mobile_money'),
  ('GN', 'Cash in person', 'cash'),
  ('GW', 'Bank transfer', 'bank_transfer'),
  ('GW', 'Mobile money', 'mobile_money'),
  ('GW', 'Cash in person', 'cash'),
  ('GY', 'Bank transfer', 'bank_transfer'),
  ('GY', 'Mobile money', 'mobile_money'),
  ('GY', 'Cash in person', 'cash'),
  ('HT', 'Bank transfer', 'bank_transfer'),
  ('HT', 'Mobile money', 'mobile_money'),
  ('HT', 'Cash in person', 'cash'),
  ('HN', 'Bank transfer', 'bank_transfer'),
  ('HN', 'Mobile money', 'mobile_money'),
  ('HN', 'Cash in person', 'cash'),
  ('HK', 'FPS', 'mobile_money'),
  ('HK', 'AlipayHK', 'ewallet'),
  ('HK', 'WeChat Pay HK', 'ewallet'),
  ('HK', 'Bank transfer', 'bank_transfer'),
  ('HK', 'Mobile money', 'mobile_money'),
  ('HK', 'Cash in person', 'cash'),
  ('HU', 'Bank transfer', 'bank_transfer'),
  ('HU', 'Mobile money', 'mobile_money'),
  ('HU', 'Cash in person', 'cash'),
  ('IS', 'Bank transfer', 'bank_transfer'),
  ('IS', 'Mobile money', 'mobile_money'),
  ('IS', 'Cash in person', 'cash'),
  ('IN', 'UPI', 'mobile_money'),
  ('IN', 'Paytm', 'ewallet'),
  ('IN', 'PhonePe', 'mobile_money'),
  ('IN', 'Google Pay', 'mobile_money'),
  ('IN', 'IMPS bank transfer', 'bank_transfer'),
  ('IN', 'Bank transfer', 'bank_transfer'),
  ('IN', 'Mobile money', 'mobile_money'),
  ('IN', 'Cash in person', 'cash'),
  ('ID', 'GoPay', 'mobile_money'),
  ('ID', 'OVO', 'ewallet'),
  ('ID', 'DANA', 'ewallet'),
  ('ID', 'ShopeePay', 'ewallet'),
  ('ID', 'Bank transfer', 'bank_transfer'),
  ('ID', 'Mobile money', 'mobile_money'),
  ('ID', 'Cash in person', 'cash'),
  ('IR', 'Bank transfer', 'bank_transfer'),
  ('IR', 'Mobile money', 'mobile_money'),
  ('IR', 'Cash in person', 'cash'),
  ('IQ', 'ZainCash', 'mobile_money'),
  ('IQ', 'FastPay', 'mobile_money'),
  ('IQ', 'Bank transfer', 'bank_transfer'),
  ('IQ', 'Mobile money', 'mobile_money'),
  ('IQ', 'Cash in person', 'cash'),
  ('IE', 'Revolut', 'ewallet'),
  ('IE', 'SEPA transfer', 'bank_transfer'),
  ('IE', 'Bank transfer', 'bank_transfer'),
  ('IE', 'Mobile money', 'mobile_money'),
  ('IE', 'Cash in person', 'cash'),
  ('IM', 'Bank transfer', 'bank_transfer'),
  ('IM', 'Mobile money', 'mobile_money'),
  ('IM', 'Cash in person', 'cash'),
  ('IL', 'Bit', 'mobile_money'),
  ('IL', 'PayBox', 'mobile_money'),
  ('IL', 'Bank transfer', 'bank_transfer'),
  ('IL', 'Mobile money', 'mobile_money'),
  ('IL', 'Cash in person', 'cash'),
  ('IT', 'SEPA transfer', 'bank_transfer'),
  ('IT', 'PayPal', 'ewallet'),
  ('IT', 'PostePay', 'card'),
  ('IT', 'Bank transfer', 'bank_transfer'),
  ('IT', 'Mobile money', 'mobile_money'),
  ('IT', 'Cash in person', 'cash'),
  ('CI', 'Orange Money', 'mobile_money'),
  ('CI', 'MTN MoMo', 'mobile_money'),
  ('CI', 'Wave', 'mobile_money'),
  ('CI', 'Bank transfer', 'bank_transfer'),
  ('CI', 'Mobile money', 'mobile_money'),
  ('CI', 'Cash in person', 'cash'),
  ('JM', 'Bank transfer', 'bank_transfer'),
  ('JM', 'Mobile money', 'mobile_money'),
  ('JM', 'Cash in person', 'cash'),
  ('JP', 'PayPay', 'mobile_money'),
  ('JP', 'LINE Pay', 'ewallet'),
  ('JP', 'Bank transfer', 'bank_transfer'),
  ('JP', 'Mobile money', 'mobile_money'),
  ('JP', 'Cash in person', 'cash'),
  ('JE', 'Bank transfer', 'bank_transfer'),
  ('JE', 'Mobile money', 'mobile_money'),
  ('JE', 'Cash in person', 'cash'),
  ('JO', 'Bank transfer', 'bank_transfer'),
  ('JO', 'Mobile money', 'mobile_money'),
  ('JO', 'Cash in person', 'cash'),
  ('KE', 'M-Pesa', 'mobile_money'),
  ('KE', 'Airtel Money', 'mobile_money'),
  ('KE', 'Equity Bank', 'bank_transfer'),
  ('KE', 'Bank transfer', 'bank_transfer'),
  ('KE', 'Mobile money', 'mobile_money'),
  ('KE', 'Cash in person', 'cash'),
  ('KI', 'Bank transfer', 'bank_transfer'),
  ('KI', 'Mobile money', 'mobile_money'),
  ('KI', 'Cash in person', 'cash'),
  ('XK', 'Bank transfer', 'bank_transfer'),
  ('XK', 'Mobile money', 'mobile_money'),
  ('XK', 'Cash in person', 'cash'),
  ('KW', 'Bank transfer', 'bank_transfer'),
  ('KW', 'Mobile money', 'mobile_money'),
  ('KW', 'Cash in person', 'cash'),
  ('KG', 'Bank transfer', 'bank_transfer'),
  ('KG', 'Mobile money', 'mobile_money'),
  ('KG', 'Cash in person', 'cash'),
  ('LA', 'Bank transfer', 'bank_transfer'),
  ('LA', 'Mobile money', 'mobile_money'),
  ('LA', 'Cash in person', 'cash'),
  ('LV', 'Bank transfer', 'bank_transfer'),
  ('LV', 'Mobile money', 'mobile_money'),
  ('LV', 'Cash in person', 'cash'),
  ('LB', 'Bank transfer', 'bank_transfer'),
  ('LB', 'Mobile money', 'mobile_money'),
  ('LB', 'Cash in person', 'cash'),
  ('LS', 'Bank transfer', 'bank_transfer'),
  ('LS', 'Mobile money', 'mobile_money'),
  ('LS', 'Cash in person', 'cash'),
  ('LR', 'Bank transfer', 'bank_transfer'),
  ('LR', 'Mobile money', 'mobile_money'),
  ('LR', 'Cash in person', 'cash'),
  ('LY', 'Bank transfer', 'bank_transfer'),
  ('LY', 'Mobile money', 'mobile_money'),
  ('LY', 'Cash in person', 'cash'),
  ('LI', 'Bank transfer', 'bank_transfer'),
  ('LI', 'Mobile money', 'mobile_money'),
  ('LI', 'Cash in person', 'cash'),
  ('LT', 'Bank transfer', 'bank_transfer'),
  ('LT', 'Mobile money', 'mobile_money'),
  ('LT', 'Cash in person', 'cash'),
  ('LU', 'Bank transfer', 'bank_transfer'),
  ('LU', 'Mobile money', 'mobile_money'),
  ('LU', 'Cash in person', 'cash'),
  ('MO', 'Bank transfer', 'bank_transfer'),
  ('MO', 'Mobile money', 'mobile_money'),
  ('MO', 'Cash in person', 'cash'),
  ('MG', 'Bank transfer', 'bank_transfer'),
  ('MG', 'Mobile money', 'mobile_money'),
  ('MG', 'Cash in person', 'cash'),
  ('MW', 'Airtel Money', 'mobile_money'),
  ('MW', 'TNM Mpamba', 'mobile_money'),
  ('MW', 'Bank transfer', 'bank_transfer'),
  ('MW', 'Mobile money', 'mobile_money'),
  ('MW', 'Cash in person', 'cash'),
  ('MY', 'Touch n Go', 'ewallet'),
  ('MY', 'GrabPay', 'ewallet'),
  ('MY', 'FPX bank transfer', 'bank_transfer'),
  ('MY', 'Bank transfer', 'bank_transfer'),
  ('MY', 'Mobile money', 'mobile_money'),
  ('MY', 'Cash in person', 'cash'),
  ('MV', 'Bank transfer', 'bank_transfer'),
  ('MV', 'Mobile money', 'mobile_money'),
  ('MV', 'Cash in person', 'cash'),
  ('ML', 'Orange Money', 'mobile_money'),
  ('ML', 'Wave', 'mobile_money'),
  ('ML', 'Bank transfer', 'bank_transfer'),
  ('ML', 'Mobile money', 'mobile_money'),
  ('ML', 'Cash in person', 'cash'),
  ('MT', 'Bank transfer', 'bank_transfer'),
  ('MT', 'Mobile money', 'mobile_money'),
  ('MT', 'Cash in person', 'cash'),
  ('MH', 'Bank transfer', 'bank_transfer'),
  ('MH', 'Mobile money', 'mobile_money'),
  ('MH', 'Cash in person', 'cash'),
  ('MQ', 'Bank transfer', 'bank_transfer'),
  ('MQ', 'Mobile money', 'mobile_money'),
  ('MQ', 'Cash in person', 'cash'),
  ('MR', 'Bank transfer', 'bank_transfer'),
  ('MR', 'Mobile money', 'mobile_money'),
  ('MR', 'Cash in person', 'cash'),
  ('MU', 'Bank transfer', 'bank_transfer'),
  ('MU', 'Mobile money', 'mobile_money'),
  ('MU', 'Cash in person', 'cash'),
  ('YT', 'Bank transfer', 'bank_transfer'),
  ('YT', 'Mobile money', 'mobile_money'),
  ('YT', 'Cash in person', 'cash'),
  ('MX', 'SPEI', 'bank_transfer'),
  ('MX', 'Mercado Pago', 'ewallet'),
  ('MX', 'OXXO cash', 'cash'),
  ('MX', 'Bank transfer', 'bank_transfer'),
  ('MX', 'Mobile money', 'mobile_money'),
  ('MX', 'Cash in person', 'cash'),
  ('FM', 'Bank transfer', 'bank_transfer'),
  ('FM', 'Mobile money', 'mobile_money'),
  ('FM', 'Cash in person', 'cash'),
  ('MD', 'Bank transfer', 'bank_transfer'),
  ('MD', 'Mobile money', 'mobile_money'),
  ('MD', 'Cash in person', 'cash'),
  ('MC', 'Bank transfer', 'bank_transfer'),
  ('MC', 'Mobile money', 'mobile_money'),
  ('MC', 'Cash in person', 'cash'),
  ('MN', 'Bank transfer', 'bank_transfer'),
  ('MN', 'Mobile money', 'mobile_money'),
  ('MN', 'Cash in person', 'cash'),
  ('ME', 'Bank transfer', 'bank_transfer'),
  ('ME', 'Mobile money', 'mobile_money'),
  ('ME', 'Cash in person', 'cash'),
  ('MS', 'Bank transfer', 'bank_transfer'),
  ('MS', 'Mobile money', 'mobile_money'),
  ('MS', 'Cash in person', 'cash'),
  ('MA', 'Cash Plus', 'mobile_money'),
  ('MA', 'Bank transfer', 'bank_transfer'),
  ('MA', 'Mobile money', 'mobile_money'),
  ('MA', 'Cash in person', 'cash'),
  ('MZ', 'Bank transfer', 'bank_transfer'),
  ('MZ', 'Mobile money', 'mobile_money'),
  ('MZ', 'Cash in person', 'cash'),
  ('MM', 'KBZPay', 'mobile_money'),
  ('MM', 'Wave Money', 'mobile_money'),
  ('MM', 'Bank transfer', 'bank_transfer'),
  ('MM', 'Mobile money', 'mobile_money'),
  ('MM', 'Cash in person', 'cash'),
  ('NA', 'Bank transfer', 'bank_transfer'),
  ('NA', 'Mobile money', 'mobile_money'),
  ('NA', 'Cash in person', 'cash'),
  ('NR', 'Bank transfer', 'bank_transfer'),
  ('NR', 'Mobile money', 'mobile_money'),
  ('NR', 'Cash in person', 'cash'),
  ('NP', 'eSewa', 'ewallet'),
  ('NP', 'Khalti', 'ewallet'),
  ('NP', 'Bank transfer', 'bank_transfer'),
  ('NP', 'Mobile money', 'mobile_money'),
  ('NP', 'Cash in person', 'cash'),
  ('NL', 'iDEAL', 'bank_transfer'),
  ('NL', 'SEPA transfer', 'bank_transfer'),
  ('NL', 'Tikkie', 'mobile_money'),
  ('NL', 'Bank transfer', 'bank_transfer'),
  ('NL', 'Mobile money', 'mobile_money'),
  ('NL', 'Cash in person', 'cash'),
  ('NC', 'Bank transfer', 'bank_transfer'),
  ('NC', 'Mobile money', 'mobile_money'),
  ('NC', 'Cash in person', 'cash'),
  ('NZ', 'PayNow', 'bank_transfer'),
  ('NZ', 'Bank transfer', 'bank_transfer'),
  ('NZ', 'Mobile money', 'mobile_money'),
  ('NZ', 'Cash in person', 'cash'),
  ('NI', 'Bank transfer', 'bank_transfer'),
  ('NI', 'Mobile money', 'mobile_money'),
  ('NI', 'Cash in person', 'cash'),
  ('NE', 'Bank transfer', 'bank_transfer'),
  ('NE', 'Mobile money', 'mobile_money'),
  ('NE', 'Cash in person', 'cash'),
  ('NG', 'OPay', 'mobile_money'),
  ('NG', 'PalmPay', 'mobile_money'),
  ('NG', 'Kuda', 'bank_transfer'),
  ('NG', 'Bank transfer', 'bank_transfer'),
  ('NG', 'Mobile money', 'mobile_money'),
  ('NG', 'Cash in person', 'cash'),
  ('NU', 'Bank transfer', 'bank_transfer'),
  ('NU', 'Mobile money', 'mobile_money'),
  ('NU', 'Cash in person', 'cash'),
  ('NF', 'Bank transfer', 'bank_transfer'),
  ('NF', 'Mobile money', 'mobile_money'),
  ('NF', 'Cash in person', 'cash'),
  ('KP', 'Bank transfer', 'bank_transfer'),
  ('KP', 'Mobile money', 'mobile_money'),
  ('KP', 'Cash in person', 'cash'),
  ('MK', 'Bank transfer', 'bank_transfer'),
  ('MK', 'Mobile money', 'mobile_money'),
  ('MK', 'Cash in person', 'cash'),
  ('MP', 'Bank transfer', 'bank_transfer'),
  ('MP', 'Mobile money', 'mobile_money'),
  ('MP', 'Cash in person', 'cash'),
  ('NO', 'Vipps', 'mobile_money'),
  ('NO', 'Bank transfer', 'bank_transfer'),
  ('NO', 'Mobile money', 'mobile_money'),
  ('NO', 'Cash in person', 'cash'),
  ('OM', 'Bank transfer', 'bank_transfer'),
  ('OM', 'Mobile money', 'mobile_money'),
  ('OM', 'Cash in person', 'cash'),
  ('PK', 'JazzCash', 'mobile_money'),
  ('PK', 'Easypaisa', 'mobile_money'),
  ('PK', 'SadaPay', 'ewallet'),
  ('PK', 'Bank transfer', 'bank_transfer'),
  ('PK', 'Mobile money', 'mobile_money'),
  ('PK', 'Cash in person', 'cash'),
  ('PW', 'Bank transfer', 'bank_transfer'),
  ('PW', 'Mobile money', 'mobile_money'),
  ('PW', 'Cash in person', 'cash'),
  ('PS', 'Bank transfer', 'bank_transfer'),
  ('PS', 'Mobile money', 'mobile_money'),
  ('PS', 'Cash in person', 'cash'),
  ('PA', 'Bank transfer', 'bank_transfer'),
  ('PA', 'Mobile money', 'mobile_money'),
  ('PA', 'Cash in person', 'cash'),
  ('PG', 'Bank transfer', 'bank_transfer'),
  ('PG', 'Mobile money', 'mobile_money'),
  ('PG', 'Cash in person', 'cash'),
  ('PY', 'Bank transfer', 'bank_transfer'),
  ('PY', 'Mobile money', 'mobile_money'),
  ('PY', 'Cash in person', 'cash'),
  ('PE', 'Yape', 'mobile_money'),
  ('PE', 'Plin', 'mobile_money'),
  ('PE', 'Bank transfer', 'bank_transfer'),
  ('PE', 'Mobile money', 'mobile_money'),
  ('PE', 'Cash in person', 'cash'),
  ('PH', 'GCash', 'mobile_money'),
  ('PH', 'Maya', 'ewallet'),
  ('PH', 'Coins.ph', 'ewallet'),
  ('PH', 'Bank transfer', 'bank_transfer'),
  ('PH', 'Mobile money', 'mobile_money'),
  ('PH', 'Cash in person', 'cash'),
  ('PN', 'Bank transfer', 'bank_transfer'),
  ('PN', 'Mobile money', 'mobile_money'),
  ('PN', 'Cash in person', 'cash'),
  ('PL', 'BLIK', 'mobile_money'),
  ('PL', 'SEPA transfer', 'bank_transfer'),
  ('PL', 'Bank transfer', 'bank_transfer'),
  ('PL', 'Mobile money', 'mobile_money'),
  ('PL', 'Cash in person', 'cash'),
  ('PT', 'MB WAY', 'mobile_money'),
  ('PT', 'SEPA transfer', 'bank_transfer'),
  ('PT', 'Bank transfer', 'bank_transfer'),
  ('PT', 'Mobile money', 'mobile_money'),
  ('PT', 'Cash in person', 'cash'),
  ('QA', 'Bank transfer', 'bank_transfer'),
  ('QA', 'Mobile money', 'mobile_money'),
  ('QA', 'Cash in person', 'cash'),
  ('RO', 'Bank transfer', 'bank_transfer'),
  ('RO', 'Mobile money', 'mobile_money'),
  ('RO', 'Cash in person', 'cash'),
  ('RW', 'MTN MoMo', 'mobile_money'),
  ('RW', 'Airtel Money', 'mobile_money'),
  ('RW', 'Bank transfer', 'bank_transfer'),
  ('RW', 'Mobile money', 'mobile_money'),
  ('RW', 'Cash in person', 'cash'),
  ('RE', 'Bank transfer', 'bank_transfer'),
  ('RE', 'Mobile money', 'mobile_money'),
  ('RE', 'Cash in person', 'cash'),
  ('BL', 'Bank transfer', 'bank_transfer'),
  ('BL', 'Mobile money', 'mobile_money'),
  ('BL', 'Cash in person', 'cash'),
  ('KN', 'Bank transfer', 'bank_transfer'),
  ('KN', 'Mobile money', 'mobile_money'),
  ('KN', 'Cash in person', 'cash'),
  ('LC', 'Bank transfer', 'bank_transfer'),
  ('LC', 'Mobile money', 'mobile_money'),
  ('LC', 'Cash in person', 'cash'),
  ('MF', 'Bank transfer', 'bank_transfer'),
  ('MF', 'Mobile money', 'mobile_money'),
  ('MF', 'Cash in person', 'cash'),
  ('PM', 'Bank transfer', 'bank_transfer'),
  ('PM', 'Mobile money', 'mobile_money'),
  ('PM', 'Cash in person', 'cash'),
  ('VC', 'Bank transfer', 'bank_transfer'),
  ('VC', 'Mobile money', 'mobile_money'),
  ('VC', 'Cash in person', 'cash'),
  ('WS', 'Bank transfer', 'bank_transfer'),
  ('WS', 'Mobile money', 'mobile_money'),
  ('WS', 'Cash in person', 'cash'),
  ('SM', 'Bank transfer', 'bank_transfer'),
  ('SM', 'Mobile money', 'mobile_money'),
  ('SM', 'Cash in person', 'cash'),
  ('SA', 'STC Pay', 'mobile_money'),
  ('SA', 'Mada', 'card'),
  ('SA', 'Bank transfer', 'bank_transfer'),
  ('SA', 'Mobile money', 'mobile_money'),
  ('SA', 'Cash in person', 'cash'),
  ('SN', 'Wave', 'mobile_money'),
  ('SN', 'Orange Money', 'mobile_money'),
  ('SN', 'Bank transfer', 'bank_transfer'),
  ('SN', 'Mobile money', 'mobile_money'),
  ('SN', 'Cash in person', 'cash'),
  ('RS', 'Bank transfer', 'bank_transfer'),
  ('RS', 'Mobile money', 'mobile_money'),
  ('RS', 'Cash in person', 'cash'),
  ('SC', 'Bank transfer', 'bank_transfer'),
  ('SC', 'Mobile money', 'mobile_money'),
  ('SC', 'Cash in person', 'cash'),
  ('SL', 'Bank transfer', 'bank_transfer'),
  ('SL', 'Mobile money', 'mobile_money'),
  ('SL', 'Cash in person', 'cash'),
  ('SG', 'PayNow', 'mobile_money'),
  ('SG', 'GrabPay', 'ewallet'),
  ('SG', 'Bank transfer', 'bank_transfer'),
  ('SG', 'Mobile money', 'mobile_money'),
  ('SG', 'Cash in person', 'cash'),
  ('SX', 'Bank transfer', 'bank_transfer'),
  ('SX', 'Mobile money', 'mobile_money'),
  ('SX', 'Cash in person', 'cash'),
  ('SK', 'Bank transfer', 'bank_transfer'),
  ('SK', 'Mobile money', 'mobile_money'),
  ('SK', 'Cash in person', 'cash'),
  ('SI', 'Bank transfer', 'bank_transfer'),
  ('SI', 'Mobile money', 'mobile_money'),
  ('SI', 'Cash in person', 'cash'),
  ('SB', 'Bank transfer', 'bank_transfer'),
  ('SB', 'Mobile money', 'mobile_money'),
  ('SB', 'Cash in person', 'cash'),
  ('SO', 'EVC Plus', 'mobile_money'),
  ('SO', 'Zaad', 'mobile_money'),
  ('SO', 'Bank transfer', 'bank_transfer'),
  ('SO', 'Mobile money', 'mobile_money'),
  ('SO', 'Cash in person', 'cash'),
  ('ZA', 'Capitec', 'bank_transfer'),
  ('ZA', 'FNB eWallet', 'mobile_money'),
  ('ZA', 'Bank transfer', 'bank_transfer'),
  ('ZA', 'Mobile money', 'mobile_money'),
  ('ZA', 'Cash in person', 'cash'),
  ('GS', 'Bank transfer', 'bank_transfer'),
  ('GS', 'Mobile money', 'mobile_money'),
  ('GS', 'Cash in person', 'cash'),
  ('KR', 'KakaoPay', 'ewallet'),
  ('KR', 'Naver Pay', 'ewallet'),
  ('KR', 'Toss', 'mobile_money'),
  ('KR', 'Bank transfer', 'bank_transfer'),
  ('KR', 'Mobile money', 'mobile_money'),
  ('KR', 'Cash in person', 'cash'),
  ('SS', 'Bank transfer', 'bank_transfer'),
  ('SS', 'Mobile money', 'mobile_money'),
  ('SS', 'Cash in person', 'cash'),
  ('ES', 'SEPA transfer', 'bank_transfer'),
  ('ES', 'Bizum', 'mobile_money'),
  ('ES', 'PayPal', 'ewallet'),
  ('ES', 'Bank transfer', 'bank_transfer'),
  ('ES', 'Mobile money', 'mobile_money'),
  ('ES', 'Cash in person', 'cash'),
  ('LK', 'eZ Cash', 'mobile_money'),
  ('LK', 'Bank transfer', 'bank_transfer'),
  ('LK', 'Mobile money', 'mobile_money'),
  ('LK', 'Cash in person', 'cash'),
  ('SD', 'Bankak', 'mobile_money'),
  ('SD', 'Fawry', 'ewallet'),
  ('SD', 'Bank transfer', 'bank_transfer'),
  ('SD', 'Mobile money', 'mobile_money'),
  ('SD', 'Cash in person', 'cash'),
  ('SR', 'Bank transfer', 'bank_transfer'),
  ('SR', 'Mobile money', 'mobile_money'),
  ('SR', 'Cash in person', 'cash'),
  ('SJ', 'Bank transfer', 'bank_transfer'),
  ('SJ', 'Mobile money', 'mobile_money'),
  ('SJ', 'Cash in person', 'cash'),
  ('SE', 'Swish', 'mobile_money'),
  ('SE', 'SEPA transfer', 'bank_transfer'),
  ('SE', 'Bank transfer', 'bank_transfer'),
  ('SE', 'Mobile money', 'mobile_money'),
  ('SE', 'Cash in person', 'cash'),
  ('CH', 'TWINT', 'mobile_money'),
  ('CH', 'Bank transfer', 'bank_transfer'),
  ('CH', 'Mobile money', 'mobile_money'),
  ('CH', 'Cash in person', 'cash'),
  ('SY', 'Bank transfer', 'bank_transfer'),
  ('SY', 'Mobile money', 'mobile_money'),
  ('SY', 'Cash in person', 'cash'),
  ('ST', 'Bank transfer', 'bank_transfer'),
  ('ST', 'Mobile money', 'mobile_money'),
  ('ST', 'Cash in person', 'cash'),
  ('TW', 'LINE Pay', 'ewallet'),
  ('TW', 'Bank transfer', 'bank_transfer'),
  ('TW', 'Mobile money', 'mobile_money'),
  ('TW', 'Cash in person', 'cash'),
  ('TJ', 'Bank transfer', 'bank_transfer'),
  ('TJ', 'Mobile money', 'mobile_money'),
  ('TJ', 'Cash in person', 'cash'),
  ('TZ', 'M-Pesa', 'mobile_money'),
  ('TZ', 'Tigo Pesa', 'mobile_money'),
  ('TZ', 'Airtel Money', 'mobile_money'),
  ('TZ', 'Bank transfer', 'bank_transfer'),
  ('TZ', 'Mobile money', 'mobile_money'),
  ('TZ', 'Cash in person', 'cash'),
  ('TH', 'PromptPay', 'mobile_money'),
  ('TH', 'TrueMoney', 'ewallet'),
  ('TH', 'Bank transfer', 'bank_transfer'),
  ('TH', 'Mobile money', 'mobile_money'),
  ('TH', 'Cash in person', 'cash'),
  ('TL', 'Bank transfer', 'bank_transfer'),
  ('TL', 'Mobile money', 'mobile_money'),
  ('TL', 'Cash in person', 'cash'),
  ('TG', 'Bank transfer', 'bank_transfer'),
  ('TG', 'Mobile money', 'mobile_money'),
  ('TG', 'Cash in person', 'cash'),
  ('TK', 'Bank transfer', 'bank_transfer'),
  ('TK', 'Mobile money', 'mobile_money'),
  ('TK', 'Cash in person', 'cash'),
  ('TO', 'Bank transfer', 'bank_transfer'),
  ('TO', 'Mobile money', 'mobile_money'),
  ('TO', 'Cash in person', 'cash'),
  ('TT', 'Bank transfer', 'bank_transfer'),
  ('TT', 'Mobile money', 'mobile_money'),
  ('TT', 'Cash in person', 'cash'),
  ('TN', 'D17', 'mobile_money'),
  ('TN', 'Bank transfer', 'bank_transfer'),
  ('TN', 'Mobile money', 'mobile_money'),
  ('TN', 'Cash in person', 'cash'),
  ('TM', 'Bank transfer', 'bank_transfer'),
  ('TM', 'Mobile money', 'mobile_money'),
  ('TM', 'Cash in person', 'cash'),
  ('TC', 'Bank transfer', 'bank_transfer'),
  ('TC', 'Mobile money', 'mobile_money'),
  ('TC', 'Cash in person', 'cash'),
  ('TV', 'Bank transfer', 'bank_transfer'),
  ('TV', 'Mobile money', 'mobile_money'),
  ('TV', 'Cash in person', 'cash'),
  ('TR', 'Papara', 'ewallet'),
  ('TR', 'FAST transfer', 'bank_transfer'),
  ('TR', 'Bank transfer', 'bank_transfer'),
  ('TR', 'Mobile money', 'mobile_money'),
  ('TR', 'Cash in person', 'cash'),
  ('UG', 'MTN MoMo', 'mobile_money'),
  ('UG', 'Airtel Money', 'mobile_money'),
  ('UG', 'Bank transfer', 'bank_transfer'),
  ('UG', 'Mobile money', 'mobile_money'),
  ('UG', 'Cash in person', 'cash'),
  ('UA', 'Privat24', 'bank_transfer'),
  ('UA', 'Mono', 'bank_transfer'),
  ('UA', 'Bank transfer', 'bank_transfer'),
  ('UA', 'Mobile money', 'mobile_money'),
  ('UA', 'Cash in person', 'cash'),
  ('AE', 'PayBy', 'ewallet'),
  ('AE', 'Bank transfer', 'bank_transfer'),
  ('AE', 'Mobile money', 'mobile_money'),
  ('AE', 'Cash in person', 'cash'),
  ('GB', 'Faster Payments', 'bank_transfer'),
  ('GB', 'Revolut', 'ewallet'),
  ('GB', 'PayPal', 'ewallet'),
  ('GB', 'Monzo', 'bank_transfer'),
  ('GB', 'Bank transfer', 'bank_transfer'),
  ('GB', 'Mobile money', 'mobile_money'),
  ('GB', 'Cash in person', 'cash'),
  ('UM', 'Bank transfer', 'bank_transfer'),
  ('UM', 'Mobile money', 'mobile_money'),
  ('UM', 'Cash in person', 'cash'),
  ('VI', 'Bank transfer', 'bank_transfer'),
  ('VI', 'Mobile money', 'mobile_money'),
  ('VI', 'Cash in person', 'cash'),
  ('UY', 'Bank transfer', 'bank_transfer'),
  ('UY', 'Mobile money', 'mobile_money'),
  ('UY', 'Cash in person', 'cash'),
  ('UZ', 'Bank transfer', 'bank_transfer'),
  ('UZ', 'Mobile money', 'mobile_money'),
  ('UZ', 'Cash in person', 'cash'),
  ('VU', 'Bank transfer', 'bank_transfer'),
  ('VU', 'Mobile money', 'mobile_money'),
  ('VU', 'Cash in person', 'cash'),
  ('VE', 'Bank transfer', 'bank_transfer'),
  ('VE', 'Mobile money', 'mobile_money'),
  ('VE', 'Cash in person', 'cash'),
  ('VN', 'MoMo', 'mobile_money'),
  ('VN', 'ZaloPay', 'ewallet'),
  ('VN', 'Viettel Money', 'mobile_money'),
  ('VN', 'Bank transfer', 'bank_transfer'),
  ('VN', 'Mobile money', 'mobile_money'),
  ('VN', 'Cash in person', 'cash'),
  ('WF', 'Bank transfer', 'bank_transfer'),
  ('WF', 'Mobile money', 'mobile_money'),
  ('WF', 'Cash in person', 'cash'),
  ('YE', 'Kuraimi', 'mobile_money'),
  ('YE', 'Cash', 'cash'),
  ('YE', 'Bank transfer', 'bank_transfer'),
  ('YE', 'Mobile money', 'mobile_money'),
  ('YE', 'Cash in person', 'cash'),
  ('ZM', 'MTN MoMo', 'mobile_money'),
  ('ZM', 'Airtel Money', 'mobile_money'),
  ('ZM', 'Bank transfer', 'bank_transfer'),
  ('ZM', 'Mobile money', 'mobile_money'),
  ('ZM', 'Cash in person', 'cash'),
  ('ZW', 'EcoCash', 'mobile_money'),
  ('ZW', 'OneMoney', 'mobile_money'),
  ('ZW', 'Bank transfer', 'bank_transfer'),
  ('ZW', 'Mobile money', 'mobile_money'),
  ('ZW', 'Cash in person', 'cash'),
  ('AX', 'Bank transfer', 'bank_transfer'),
  ('AX', 'Mobile money', 'mobile_money'),
  ('AX', 'Cash in person', 'cash')
ON CONFLICT (country_iso, name) DO NOTHING;

COMMIT;
